# Generated by Django 5.2.10 on 2026-05-04 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_luggage',
            field=models.BooleanField(default=False, verbose_name='Багаж по умолчанию'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
