# Generated by Django 5.2.10 on 2026-05-04 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_schedule_bus_remove_schedule_route_booking_and_more'),
        ('buses', '0003_alter_bus_options_alter_route_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_type',
            field=models.CharField(choices=[('none', 'Без льготы'), ('pensioner', 'Пенсионер'), ('student', 'Студент'), ('disabled', 'Инвалид'), ('child', 'Ребенок до 7 лет')], default='none', max_length=20, verbose_name='Тип льготы'),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='has_luggage',
            field=models.BooleanField(default=False, verbose_name='Багаж'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(max_length=100, verbose_name='ФИО пассажира'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passport_number',
            field=models.CharField(max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.schedule', verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
